name: flutter_animated_widgets
description: A set of commonly used specific implicit animated widgets as addition on top of the default animated widgets
version: 0.3.2
publish_to: "https://forgejo.internal.iconica.nl/api/packages/internal/pub"

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^7.0.0

